language: csharp
os: linux
dist: bionic
mono: none
dotnet: 5.0
solution: TelegramBot.sln
script:
- dotnet restore
- dotnet test
branches:
  only:
  - master
  - develop
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh