language: csharp
sudo: required
dist: bionic
mono: none
dotnet: 3.0
solution: TelegramBot.sln
script:
- dotnet restore
- dotnet test
branches:
  only:
  - master
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh