language: csharp
sudo: required
dist: bionic
mono: none
dotnet: 2.2
solution: TelegramBot.sln
script:
- dotnet restore
- dotnet test
branches:
  only:
  - master
deploy:
  provider: heroku
  app: tinytinabot
  api_key:
    secure: NF4XZQD5fyXHd4touFFUb2K3X1SHzVGGYjEvH6ZrVJk29Gqa3niJArSa8iqaoYVR5Xhs/CavwwJnpp9fV03q+qyn+YJGQqTANjK/MOfL7eZIxcN1it6SGSoEkoNHsrDnr0afiPOAAkOlT6aoc5+Sfi+JZdRMBh4/9OtcJIYDxXeLsh813fyU4uziAGlLEAyzSMboKQFneHEuEeZP8yP+zLqbp4cuT6xRPHFUJp3uTXkVzOiEa0XG7OS1ngEZnmK2r3hTB+FubpFJsKrFXr/Lmk0Wkr5wL6qybwYowwx8P9Z8ApY21chEAOcfUCT7dl180v0knRQForPIPKw7qKIRO6Eo6SrRdJxyuNRsVZwjiJInPFPvXoUJTMwzVrEB78pk4RCzQorkGMGOlxXlhTUfhW5i988hVIAIZf2wcuXXq2gGONeyCqFQuc6hiVYsq9v8UCJQATGXp1i7/QznfI8WTatNdbyuHiKULRb5wktV4idOtK8JEC9hQjFMZXaokISlNPsgJwSOj6TVyI5UPZkkoWK6kCXrW0XI1+HQe7F/c04SOWneL21xFW5RjkMYzn4y5tKUYFrqpTpKqb4/WzViRdwD239anGMElPmGTG5KgQCHVFtUIEItJAqdaowZvMS/bstK2dbV2OfmyFFYbvZXhj9Qid8/mfRhjnFV9fQkfFE=
